name: dialog
version: 0.1.0
description: Modern alert, confirm and prompt dialog implementation
author: Pavel Dvořák <dvorapa@seznam.cz>
homepage: https://github.com/dvorapa/dialog-dart
environment:
  sdk: ">=1.7.0 <2.0.0"
dependencies:
  browser: ">=0.10.0 <0.11.0"