name: dialog
version: 0.2.0
description: Modern alert, confirm and prompt dialog implementation. BUGGY
author: Pavel Dvořák
homepage: https://github.com/dvorapa/dialog-dart
environment:
  sdk: ">=1.8.0 <2.0.0"
dependencies:
  browser: ">=0.10.0 <0.11.0"