name: dialog
version: 0.6.0
description: Modern alert, confirm and prompt dialog implementation
author: Pavel Dvořák <dvorapa1995@gmail.com>
homepage: https://github.com/dvorapa/dialog-dart
documentation:
environment:
  sdk: ">=1.11.1 <3.0.0"
dev_dependencies:
  build_runner: ^0.10.0
  build_web_compilers: ^0.4.0
