name: dialog
version: 0.4.1+1
description: Modern alert, confirm and prompt dialog implementation
author: Pavel Dvořák <dvorapa1995@gmail.com>
homepage: https://github.com/dvorapa/dialog-dart
documentation:
environment:
  sdk: ">=1.11.1 <2.0.0"
dependencies:
  browser: ">=0.10.0 <0.11.0"